name: Pull Request Checks

on:
  pull_request:

jobs:
  check-format:
    name: Check Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Get pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Check format
        id: format-check
        run: pnpm format:check

      - name: Prettier Output
        if: ${{ failure() }}
        run: |
          echo "Prettier found formatting issues (see logs above). To fix these issues, run 'pnpm format' locally."

      - name: Lint
        id: lint-check
        run: pnpm lint

      - name: Lint Output
        if: ${{ failure() }}
        run: echo "ESLint found linting issues (see logs above). Run 'pnpm lint' locally and fix the issues."

      - name: Typecheck
        id: typecheck
        run: pnpm typecheck

      - name: Typecheck Output
        if: ${{ failure() }}
        run: echo "TypeScript found type errors (see logs above). Run 'pnpm typecheck' locally and fix the issues."
